feat: Optionally allow selecting segment with a single click
omegat-org/omegat pull request #1053
Opened 2024-06-09 03:51 UTC by miurahr

- Add Preference.SINGLE_CLICK_SEGMENT_ACTIVATION
- Add checkbox for controlling single-click-activation of segments
- Make single-click activation of segments depends on cursor-lock-mode
- Allow single click to activate segment
- Single click moves cursor to the word pointed

## Pull request type

Please mark github LABEL of the type of change your PR introduces:

- Bug fix -> [bug]
- Feature enhancement -> [enhancement]
- Documentation -> [documentation]
- Build and release changes -> [build/release]
- Other (describe below)

## Which ticket is resolved?

- Title ex. fix...
  * URL ex. https://...
 
- Title
  * URL

## What does this PR change?

-
-
-

## Other information

2025-06-14 13:40 UTC, miurahr commented
Raised the document issue ticket.

2025-06-14 13:42 UTC, miurahr commented
There has been no review comment in 2 months. I will merge it soon.

2025-06-14 13:57 UTC, brandelune requested changes

2025-06-14 13:57 UTC, brandelune commented on src/org/omegat/Bundle.properties
> +WF_OPTION_ALLOW_SELECT_SINGLE_CLICK=Activate segment with single click (Feature is only active while the cursor is locked.)
- The layout in the preference window does not work. The string is too long and pushes the other half of the window all the way to the left.
- The comment in parenthesis is due in the manual, not in the preference.

2025-06-15 05:13 UTC, miurahr commented
> > Raised the document issue ticket.
> 
> The author should update the manual.

update manual source.

2025-06-15 05:30 UTC, Kazephil commented
> > > Raised the document issue ticket.
> > 
> > The author should update the manual.
> 
> update manual source.

Give me a day or two to review the text of the manual.

2025-06-15 13:04 UTC, Kazephil reviewed
I just pushed a suggestion for tightening up the description of the feature in the manual. Let me know what you think.

Also, where were the instructions for building just the manual with this new Gradle-based system? I can't seem to find them.

2025-06-16 03:37 UTC, Kazephil commented on src_docs/manual/en/OmegaT_Preferences.xml
> +				<para>By default, OmegaT requires a double-click to enter the segment under the cursor. Use this option if you prefer to enter segments with a single-click.</para>
I'll see your modification, and raise you a tweak! :grin:

2025-06-21 04:17 UTC, miurahr commented
@brandelune  @Kazephil  do you have any further actions? There is no confirmation and been in request for changes. but there is no obvious request now.

2025-06-21 23:21 UTC, Kazephil approved these changes
I think it's fine if @brandelune is happy with my last tweak to his modification.

2025-06-22 05:49 UTC, brandelune approved these changes

2025-06-22 05:50 UTC, merged