feat: preference for paragraph from segmented tmx
omegat-org/omegat pull request #1217
Opened 2024-12-17 15:13 UTC by miurahr

## Pull request type

- Feature enhancement -> [enhancement]

## Which ticket is resolved?

-    FindMatcher always search separate segment match without penalty
-    https://sourceforge.net/p/omegat/bugs/1251/

## What does this PR change?

- split #963 
- Add preference for paragraph from separated tmx

## Other information

2024-12-18 04:21 UTC, brandelune commented on src/org/omegat/Bundle.properties
I’m not sure that preference is very clear to the user.
<img width="564" alt="Screen Shot 2024-12-18 at 13 20 45" src="https://github.com/user-attachments/assets/2bfb1368-d7f4-4c89-9e39-38db05938f2a" />

2024-12-18 04:26 UTC, brandelune requested changes

2024-12-18 04:26 UTC, brandelune commented on src/org/omegat/Bundle.properties
The format should be [✓] Verb + information

2024-12-18 04:26 UTC, brandelune commented on src/org/omegat/Bundle.properties
@Kazephil what is your take on this?

2024-12-19 02:57 UTC, miurahr commented on src/org/omegat/Bundle.properties
Try to explain fully.

- Show a paragraph as a match result which is constructed from words of segmented matches of segmented internal and external TMXs matched by segmented items of source text on the fuzzy-matches pane on a project configured as no segmentation.

2024-12-19 08:08 UTC, brandelune commented on src/org/omegat/Bundle.properties
What about something like this: 

```
Display matches constructed from multiple segments
```
This option should only be available when the project is in paragraph mode, and there should be a complement in the documentation (as is planned).

What do you think about that?

2024-12-19 08:39 UTC, miurahr commented on src/org/omegat/Bundle.properties
@Kazephil how do you think?

2024-12-19 08:42 UTC, miurahr commented on src/org/omegat/Bundle.properties
> This option should only be available when the project is in paragraph mode, and there should be a complement in the documentation (as is planned).

The option is on user option preference, not project preference.

2024-12-21 01:14 UTC, Kazephil commented on src/org/omegat/Bundle.properties
I'm not entirely sure I understand exactly what this feature does, but based on the original UI message proposal, Jean-Christophe's suggestion, and the rest of the conversation, I would suggest:

`When using paragraph segmentation, show matches assembled from multiple segments.`

Also, is that a feature that applies to the penalty for matches from another language? That's the way it looks like in the screenshot above, but the description in this conversation suggests that it's not related to matches in another language.

2024-12-21 01:29 UTC, miurahr commented on src/org/omegat/Bundle.properties
> I'm not entirely sure I understand exactly what this feature does, but based on the original UI message proposal, Jean-Christophe's suggestion, and the rest of the conversation, I would suggest:
> 
> `When using paragraph segmentation, show matches assembled from multiple segments.`

It looks like matches are come from "multiple paragraph" search, because "paragraph segmentation" used. The feature does "multiple (segmented) words (generated by paragraph)". and the candidates are optional/alternative for normal matches. So I suggest adding "show also".

> Also, is that a feature that applies to the penalty for matches from another language? That's the way it looks like in the screenshot above, but the description in this conversation suggests that it's not related to matches in another language.

The feature treat a penalty properly, but the feature does not direct relation with the foreign language match.

2024-12-21 01:30 UTC, miurahr commented on src/org/omegat/Bundle.properties
@Kazephil  please check also #1218 that updates manual description for the feature.

2024-12-21 04:35 UTC, brandelune commented on src/org/omegat/Bundle.properties
> > This option should only be available when the project is in paragraph mode, and there should be a complement in the documentation (as is planned).
> 
> The option is on user option preference, not project preference.

I know. But it is not relevant (and confusing) when the project uses sentence segmentation. OmegaT should be able to detect which options are relevant based on the project preferences.

2024-12-21 04:38 UTC, brandelune commented on src/org/omegat/Bundle.properties
> Also, is that a feature that applies to the penalty for matches from another language? That's the way it looks like in the screenshot above, but the description in this conversation suggests that it's not related to matches in another language.

No. It is just that the "penalty for other languages" preference should be properly indented to be visually dependent on the relevant checkbox. @miurahr would you mind checking if it is possible to indent the "penalty for other languages" preference?

2024-12-21 07:49 UTC, t-cordonnier commented on src/org/omegat/Bundle.properties
I agree, the actual indentation gave me the same impression even if I perfectly knew that the option is not related.
Maybe we could increase indentation of options under "Settings for tags"

2024-12-21 07:58 UTC, Kazephil commented on src/org/omegat/Bundle.properties
I have just pushed a suggested revisions to the manual updates.

My new best suggestion is simply:
`Show matches assembled from multiple segments`

2024-12-21 08:04 UTC, Kazephil commented on src/org/omegat/Bundle.properties
> I agree, the actual indentation gave me the same impression even if I perfectly knew that the option is not related. Maybe we could increase indentation of options under "Settings for tags"

Or add an extra line above the new option. Or even both! :grin: 

At the very least, it would certainly look better if the `Penalty for matches in other languages` phrase at least lined up with the checkboxes for the other options under `Settings for tags`,

2025-03-05 13:45 UTC, miurahr commented
@brandelune  why still block?

2025-03-05 23:55 UTC, miurahr commented
> > @brandelune why still block?
> 
> Because @Kazephil’s suggestion is not implemented:
> 
> > I have just pushed suggested revisions to the manual updates.
> > My new best suggestion is simply: `Show matches assembled from multiple segments`
> 
> Also, the indent is not correct:


The PR here adding preference option for segmented match. If another option has wrong UI visual, 
 it is another bug out of scope of the feature proposal.

![Screenshot from 2025-03-06 08-43-02](https://github.com/user-attachments/assets/f2689493-9cf4-4a3d-a265-0ac741caf49e)

I have inserted description for the option. You suggest a removal of indent that is not possible by NetBeans GUI editor, at least by my UI skill, because the indent sizes have been already ZERO, so I declined it. I can increase indent, so I insert some adjustment for existing label.

2025-03-06 00:05 UTC, miurahr commented
I have merged the master branch to synchronize the Gradle build script changes.

2025-03-06 06:41 UTC, brandelune commented
> I have merged the master branch to synchronize the Gradle build script changes.

The merging seems to have broken something:

`./gradlew -PforceSkipDocumentBuild=1 installDist` fails because `limactl` is stopped.

2025-03-06 08:28 UTC, Kazephil commented
@brandelune
It builds fine here both from IDEA and the command line.

2025-03-06 08:33 UTC, brandelune commented
```
Repositories/omegat.org  topic/miurahr/matches/preference-of-segmented-matches $ ./gradlew -PforceSkipDocumentBuild=1 installDist

> Configure project :
6.1.0
Detected revision 0c1768aa5

> Task :firstStepsCa
create target folder ../build/docs/greetings/ca
select container CLI: /opt/local/bin/nerdctl
time="2025-03-06T09:32:24+01:00" level=fatal msg="instance \"default\" is stopped, run `limactl start default` to start the instance"
time="2025-03-06T09:32:24+01:00" level=fatal msg="instance \"default\" is stopped, run `limactl start default` to start the instance"

> Task :firstStepsCa FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':firstStepsCa'.
> Process 'command './docgen'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Get more help at https://help.gradle.org.

BUILD FAILED in 9s
8 actionable tasks: 1 executed, 7 up-to-date
```

2025-03-06 08:47 UTC, Kazephil commented
Strange. Do you get the same error on other branches?

From the directory with my OmegaT repository, with `git status` showing that I'm on the `topic/miurahr/matches/preference-of-segmented-matches` branch, I get:

```
$ ./gradlew -PforceSkipDocumentBuild=1 installDist
NOTE: Picked up JDK_JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.de

> Configure project :
6.1.0
Detected revision 0c1768aa5

BUILD SUCCESSFUL in 41s
244 actionable tasks: 3 executed, 241 up-to-date
```

This is on a Linux system. I can give it a try on a Windows 11 system after I get a chance to finish setting it up.

2025-03-06 15:17 UTC, brandelune commented
> > Because @Kazephil’s suggestion is not implemented:
> > > I have just pushed suggested revisions to the manual updates.
> > > My new best suggestion is simply: `Show matches assembled from multiple segments`
> > 
> > 
> > Also, the indent is not correct:

Ok. The layout seems to be fixed, and we just need @Kazephil to implement his modification :-)

2025-03-07 12:53 UTC, miurahr commented on src/org/omegat/Bundle.properties
> +PARAGRAPH_MATCH_FROM_SEGMENT_TMX=Paragraph from segment matches of segmented TMX on a non-segment project
```suggestion
EXT_SEGMENTED_DESCRIPTION=Settings for segmented TMX on a non-segment project:
PARAGRAPH_MATCH_FROM_SEGMENT_TMX= Show matches assembled from multiple segments
```

2025-03-10 09:16 UTC, miurahr commented on src/org/omegat/Bundle.properties
> +EXT_SEGMENTED_DESCRIPTION=Settings for segmented TMX on a non-segment project:
```suggestion
EXT_SEGMENTED_DESCRIPTION=When using paragraph segmentation:
```

2025-03-10 09:58 UTC, Kazephil approved these changes

2025-03-10 09:58 UTC, Kazephil commented on src/org/omegat/Bundle.properties
> +EXT_SEGMENTED_DESCRIPTION=Settings for segmented TMX on a non-segment project:
Looks good. I just implemented the change and pushed it.

2025-03-10 15:13 UTC, merged