linux installation files by Marc Prior
omegat-org/omegat pull request #242
Opened 2022-08-21 17:45 UTC by brandelune

- [ ] Bug fix
- [X] Feature
- [ ] Documentation
- [ ] Build and release changes
- [ ] Other (describe below)

## Which ticket is resolved?

https://sourceforge.net/p/omegat/feature-requests/1626/

## What does this PR change?

Marc updated his install script based on recent discussions.

2022-08-21 17:49 UTC, brandelune commented
The new linux-install.readme file should be included in the distribution but I've not yet modified the build script.

2022-08-23 22:39 UTC, miurahr requested changes
I don't agree with the proposed changes. It breaks many things.
I think it makes things worse.

2022-08-23 22:39 UTC, miurahr commented on release/linux-specific/linux-install.sh
> +sudo cp omegat.desktop /usr/share/applications/
It should use xdg for standard compliance. 
This removes standard compliant process. I'm against it.

2022-08-23 22:39 UTC, miurahr commented on release/linux-specific/omegat.desktop
> -Comment[ca]=l'eina lliure de memòria de traducció
Should not remove localization.

2022-08-23 22:39 UTC, miurahr commented on release/linux-specific/omegat.desktop
> +X-KDE-Username=
This remove standard properties and add KDE specific option. It is bad.

2022-08-23 22:39 UTC, miurahr commented on release/linux-specific/linux-install.sh
> +
I cannot understand why it removes parameter substitution for producing script.

2022-08-23 22:39 UTC, miurahr commented on release/linux-specific/linux-install.readme
> +SUGGESTED CHANGE:
It should not be in readme document.

2022-08-24 10:25 UTC, brandelune commented
Thank you. I understand. I'll see with Marc.

2022-09-18 14:54 UTC, brandelune commented
I think Marc is fine with you making sure that the script does not break backward compatibility. So if you feel like making the necessary modifications, go ahead so that we can include it in 5.8.

2022-12-07 03:18 UTC, brandelune commented
Let's move this to 6.1. I'll see with Marc that we fix it so that it's compatible with what you suggest. Thank you.

2023-08-22 14:43 UTC, miurahr commented
stalled.

2023-08-22 14:43 UTC, closed without merging