Add new start screen
omegat-org/omegat pull request #376
Opened 2022-12-17 16:19 UTC by brandelune

This new start screen simplifies the onboarding process by:

- stating right away where the Help/user manual is
- giving only 6 basic steps to use OmegaT
- clearly stating the freedoms granted to users

2022-12-18 08:09 UTC, Kazephil commented
I'm starting to think there might be something wrong with my system...

I can follow the logic you're using, and I'm sure you tested it and made sure it worked, but…

…for some reason, when I build the documentation on this branch, the `First_Steps.xml` file doesn't build into the `first_steps.html` file on my system, and the pane remains blank.

All the checks pass, and the application builds fine, with the title of the Editor pane showing up as First Steps, but nothing appears in the pane itself.

I'll have to see if I can break down the documentation build process to find where the problem is.

2022-12-18 10:26 UTC, brandelune commented
All those PRs are based on master. Maybe that is related.

2022-12-19 06:56 UTC, Kazephil commented
Just figured it out.
I was building only the html5 documentation, which doesn't include the First Steps page.

I got it to work, and will review it later this evening.

2022-12-19 07:44 UTC, Kazephil requested changes

2022-12-19 07:44 UTC, Kazephil commented on doc_src/en/First_Steps.xml
> +	<para>OmegaT is a free translation memory solution for professional
Replace "translation memory" with "computer-assisted translation (CAT)".
(The abbreviation isn't strictly necessary, but I prefer to include it. That's purely preference, though.)

2022-12-19 07:44 UTC, Kazephil commented on doc_src/en/First_Steps.xml
> +		your computing as you wish.</para>
I would change "and change it so it does your computing as you wish." to something closer to the GNU phrasing: "and customize it to suit your needs."

2022-12-19 07:46 UTC, Kazephil commented
I'm proposing minor tweaks, but it looks good overall.

The Readme on building the docs will also have to be updated to reflect the "instant start" --> "first steps" update.

2022-12-22 01:18 UTC, miurahr commented
@Kazephil  could you confirm?

2022-12-22 05:40 UTC, Kazephil commented
> @Kazephil could you confirm?

@miurahr 
I was waiting for @brandelune to confirm he was OK with the "one last tweak" above.

2022-12-22 05:56 UTC, brandelune commented
> > @Kazephil could you confirm?
> 
> @miurahr I was waiting for @brandelune to confirm he was OK with the "one last tweak" above.

Oh, I had missed that one.

Basically, that's a quote from the GPL site, so computing needs in board terms *but* specifically applied to OmegaT. So I think we're fine.

https://www.gnu.org/philosophy/free-sw.html#four-freedoms

2022-12-22 06:04 UTC, brandelune commented
Nice touch ;-)

2022-12-22 06:05 UTC, Kazephil commented
> Basically, that's a quote from the GPL site, so computing needs in board terms _but_ specifically applied to OmegaT. So I think we're fine.

OK. It still feels slightly off, so I just proposed a much more minor "specifically applied to OmegaT" variation in the same spirit as replacing "program" with "OmegaT".

2022-12-22 06:25 UTC, Kazephil approved these changes

2022-12-22 06:27 UTC, Kazephil commented
@miurahr 
We're good to go with this one!

2022-12-30 09:35 UTC, miurahr commented
> @miurahr We're good to go with this one!

Please also update `build.gradle`  that read `<languages>/InstantGuide.xml` @Kazephil

2022-12-30 11:01 UTC, brandelune commented
@Kazephil I'm also working on the build.gradle script to fix another issue...

2022-12-30 11:28 UTC, Kazephil commented
> @Kazephil I'm also working on the build.gradle script to fix another issue...

@brandelune 
OK. I can leave the `build.gradle` fix for `InstantGuide.xml` --> `FirstSteps.xml` up to you, then?

2023-01-04 03:25 UTC, brandelune commented
@miurahr The build process now works fine with https://github.com/omegat-org/omegat/pull/403. Please review.

2023-01-05 04:57 UTC, brandelune commented
I'll be merging all that with #403 to apply the fix and so that you can review and commit.

2023-01-06 08:31 UTC, brandelune commented
@miurahr Please use this branch to fix all the build issues that came from the new "First Steps" files.

2023-01-06 10:02 UTC, brandelune commented
This PR does this:

- add a new start screen with minimal process info and licensing info
- builds the document set to fit the current UI
- adapt the CSS to the old manuals so that they look reasonably similar to the new one
- create a multilingual index that includes languages that only have an old Instant Start tutorial

2023-01-14 12:48 UTC, brandelune reviewed
I think we should stick to the original. The GPL even as a summary can't be changed by us.

2023-01-14 13:10 UTC, Kazephil commented
> I think we should stick to the original. The GPL even as a summary can't be changed by us.

In that case, we should also stick to "the program" rather than replacing it with "OmegaT".

As far as I can tell, though, the text of the four freedoms isn't part of the text of the license, so I think we can adapt it to mâle it OmegaT-specific. We can always add an "adapted to OmegaT" section to the paragraph that introduces the freedoms.

2023-01-14 13:25 UTC, brandelune commented
> > I think we should stick to the original. The GPL even as a summary can't be changed by us.
> 
> In that case, we should also stick to "the program" rather than replacing it with "OmegaT".

You're correct that the 4 freedoms are not part of the GPL. It's just a framework to check whether a license is a free license or not.

Here, the license applies to OmegaT (and associated files), so I don't think changing "the program" to "OmegaT" is a problem.

But limiting "computing needs" to "CAT computing needs" by using the "CAT" specifier is limiting the user freedom, so I don't think it is appropriate.

2023-01-14 23:14 UTC, Kazephil commented
> But limiting "computing needs" to "CAT computing needs" by using the "CAT" specifier is limiting the user freedom, so I don't think it is appropriate. 

That's an… interesting perspective.
I still find it the highly specific "Omegat" and very broad "computing" juxtaposition slightly jarring, but I guess someone out there might want to turn OmegaT into the next Emacs that does everything except make your coffee! :grin:

2023-01-15 00:51 UTC, brandelune commented
I guess that means that one could use parts of the code to do something totally unrelated to CATing. But Emacs has not yet managed to provide coffee so I guess we should not have too many expectations with "our" code.

2023-01-15 02:36 UTC, Kazephil commented
> But Emacs has not yet managed to provide coffee

Appliances keep getting needlessly "smarter", so it might just be a matter of time! :open_mouth:

2023-01-15 04:39 UTC, Kazephil commented
Merged into `master`.

2023-01-15 04:39 UTC, closed without merging