Documentation for the x-goto functions
omegat-org/omegat pull request #378
Opened 2022-12-18 06:10 UTC by brandelune

Documentation for the functions described here:
https://github.com/omegat-org/omegat/pull/370

I've also changed the names of the menu items following my comment in the above PR.

2022-12-18 11:32 UTC, kosivantsov requested changes
`doc_src/en/HowTo_UseTM.xml`
> <itemizedlist>
	  <listitem>
		<para>either ppen the old project and put the new source

Capitalization and typo

> <listitem>
		<para>or put the reference memories that

Capitalization

2022-12-18 11:32 UTC, kosivantsov commented
Other than the requested changes, I'm very happy with this PR

2022-12-18 14:11 UTC, miurahr requested changes
Could you fix a typo?

2022-12-19 00:06 UTC, brandelune commented
I should be good now.

2022-12-19 00:21 UTC, miurahr approved these changes

2022-12-19 06:31 UTC, Kazephil requested changes

2022-12-19 06:31 UTC, Kazephil commented on doc_src/en/OmegaT5_ProjectFolder.xml
> +		  segments that have been inserted.</para>
"...to navigate to the inserted segments."

2022-12-19 06:31 UTC, Kazephil commented on doc_src/en/OmegaT5_ProjectFolder.xml
> +		  prefix, making it unnecessary to confirm these segments.</para>
I think either "without the fuzzy match prefix" or "without any prefix" would be better than "without the automatic prefix".

2022-12-19 06:32 UTC, Kazephil commented
A bit nitpicky in places, but I've proposed changes that I think make the text flow better.
Everything else looks good!

2022-12-19 07:27 UTC, brandelune commented
I'm on it.

2022-12-19 07:39 UTC, brandelune commented
I should be good now. @Kazephil can you take a last look ?

2022-12-19 08:34 UTC, kosivantsov approved these changes

2022-12-19 10:56 UTC, Kazephil requested changes
@brandelune 
Two more small changes, and you're good to go.

2022-12-19 10:56 UTC, Kazephil commented on doc_src/en/HowTo_UseTM.xml
> +		in either of the following subfolder:</para>
Last look:

Change "in either of the following subfolder:" to "in one of the following subfolders:"

2022-12-19 10:56 UTC, Kazephil commented on doc_src/en/OmegaT5_ProjectFolder.xml
> +		  segments that have been inserted.</para>
Small typo: "to navigate the" --> "to navigate to the"

2022-12-19 11:34 UTC, Kazephil approved these changes
Good to go!

2022-12-21 23:33 UTC, miurahr commented
The changes are conflict for rebase, so I just merged into master. Please don't merge master in mid of commit history, otherwise, you should use ` git rebase master`on topic branch.

2022-12-21 23:36 UTC, merged

2022-12-21 23:37 UTC, brandelune commented
> The changes are conflict for rebase, so I just merged into master. Please don't merge master in mid of commit history, otherwise, you should use ` git rebase master`on topic branch.

I'm sorry. There are still things I do not understand regarding git. I don't remember why I merged at that point.