New default layout
omegat-org/omegat pull request #431
Opened 2023-01-20 01:58 UTC by brandelune

This PR keeps the layout related commits from https://github.com/omegat-org/omegat/pull/386

2023-01-20 14:52 UTC, Kazephil commented
This one looks good here!

2023-01-22 14:02 UTC, brandelune commented
@Kazephil I just added some code to check the available screenspace so that OmegaT stays within the empty available space and does not hide behind toolbars or whatnot.

@miurahr please, check the validity of the code. It works, but it might not be the best way to put it.

2023-01-22 14:31 UTC, Kazephil commented
> I just added some code to check the available screenspace so that OmegaT stays within the empty available space and does not hide behind toolbars or whatnot.

Nice!

2023-01-22 14:34 UTC, brandelune commented
It works on macOS with the Dock on the left/right at the bottom. There is only a small glitch when the Dock is on the left, but I don't want to bother about that. The code is generic enough. Could you test that on Windows ? You'd need to remove your default OmegaT preference folder first.

2023-01-24 14:41 UTC, miurahr requested changes

2023-01-24 14:41 UTC, miurahr commented on src/org/omegat/gui/main/MainWindowUI.java
> +
Please format indent.  It may be good idea to run spotlessChangedApply task

2023-01-30 01:44 UTC, miurahr commented
Now rebased and merged into master. Thank you for hard work!

2023-01-30 01:44 UTC, closed without merging