New view options
omegat-org/omegat pull request #434
Opened 2023-01-20 02:00 UTC by brandelune

This PR keeps the view options related commits from https://github.com/omegat-org/omegat/pull/386

2023-01-23 00:32 UTC, miurahr requested changes
It should place default constants for editor in `EditorSettings` class as `private static final boolean`, not in `Preferences` class.
It is also a good habit to put implicit defaults for other settings.

2023-01-23 04:49 UTC, brandelune commented
I don't understand what you are asking me to change.

2023-01-23 06:17 UTC, miurahr requested changes

2023-01-23 06:17 UTC, miurahr commented on src/org/omegat/gui/editor/EditorSettings.java
> +                Preferences.MARK_NON_UNIQUE_SEGMENTS_DEFAULT);
```suggestion
               MARK_NON_UNIQUE_SEGMENTS_DEFAULT);
```

2023-01-23 06:17 UTC, miurahr commented on src/org/omegat/gui/editor/EditorSettings.java
> +                Preferences.MARK_GLOSSARY_MATCHES_DEFAULT);
```suggestion
                MARK_GLOSSARY_MATCHES_DEFAULT);
```

2023-01-23 06:17 UTC, miurahr commented on src/org/omegat/util/Preferences.java
> +    public static final boolean MARK_GLOSSARY_MATCHES_DEFAULT = true;
```suggestion

```

2023-01-23 06:17 UTC, miurahr commented on src/org/omegat/util/Preferences.java
> +    public static final boolean MARK_AUTOPOPULATED_DEFAULT = true;
```suggestion

```

2023-01-23 06:17 UTC, miurahr commented on src/org/omegat/util/Preferences.java
> +    public static final boolean MARK_NON_UNIQUE_SEGMENTS_DEFAULT = true;
```suggestion

```

2023-01-23 06:23 UTC, brandelune commented
I still don't understand, but I did it.

2023-01-24 03:09 UTC, miurahr commented
Reviewer cannot add a new code. You should add a constant variable definition in the class.

2023-01-25 06:29 UTC, brandelune commented
> It should place default constants for editor in `EditorSettings` class as `private static final boolean`, not in `Preferences` class.
> It is also a good habit to put implicit defaults for other settings.

If we split preference settings in all the related files, don't you think it makes it more difficult to find them ?

2023-01-27 01:49 UTC, miurahr commented
> > It should place default constants for editor in `EditorSettings` class as `private static final boolean`, not in `Preferences` class.
> > It is also a good habit to put implicit defaults for other settings.
> 
> If we split preference settings in all the related files, don't you think it makes it more difficult to find them ?

I don't understand what you want to do.

There is a golden rule for object-oriented programming.
All the related properties, methods are going to be inside the class.

I think as follows based on the OOP rule.
Keys of preferences are properties (constant) of Preferences class. 
The default values (constant ) of  Editor behavior  are properties of  Editor GUI parts, so it should  belong to `EditorSettings` class.

I think that finding variable is a task of IDE, cross reference tools, or other computer-assisted programming environment, especially in large project in Java ecosystem.

2023-01-27 01:58 UTC, brandelune commented
> I don't understand what you want to do.
> 
> There is a golden rule for object-oriented programming. All the related properties, methods are going to be inside the class.

I'm fine with golden rules, but I'm just changing 5 default preferences in the _current_ version of the code.

> I think as follows based on the OOP rule. Keys of preferences are properties (constant) of Preferences class. The default values (constant ) of Editor behavior are properties of Editor GUI parts, so it should belong to `EditorSettings` class.

If we want to reorganize the whole preference code to be closer to the traditional OOP rules, we can do that in 6.1.

2023-01-27 06:12 UTC, miurahr commented
> > I don't understand what you want to do.
> > There is a golden rule for object-oriented programming. All the related properties, methods are going to be inside the class.
> 
> I'm fine with golden rules, but I'm just changing 5 default preferences in the _current_ version of the code.
> 
> > I think as follows based on the OOP rule. Keys of preferences are properties (constant) of Preferences class. The default values (constant ) of Editor behavior are properties of Editor GUI parts, so it should belong to `EditorSettings` class.
> 
> If we want to reorganize the whole preference code to be closer to the traditional OOP rules, we can do that in 6.1.

I just comment about your 5 default preferences. I don't understand why you tell whole preference code.

2023-01-27 06:22 UTC, brandelune commented
Sorry, maybe there is a confusion.

Is there any problem with the current proposals ?

2023-01-28 09:32 UTC, miurahr commented
There is no big problem in current code; except for failure of build.


I want to understand a reason why default value should be in Preferences class.

In many cases,  OmegaT code use direct value for defaults. Some put its default as  class constant,  and very rare who put it in Preferences class.

It may be a good change to improve Preferences system when we find something not optimal in the system.

There can be an idea to put defaults values in external file such as `PreferenesDefaults.properties` and developer and manual editor can share its values. This may help document writer to understand  behaviors.
Is it your concerned?

2023-01-28 13:41 UTC, brandelune commented
> There is no big problem in current code; except for failure of build.

When I merge master on this branch it builds fine.
 
> I want to understand a reason why default value should be in Preferences class.

I see.
 
> In many cases, OmegaT code use direct value for defaults. Some put its default as class constant, and very rare who put it in Preferences class.

I see.
 
> It may be a good change to improve Preferences system when we find something not optimal in the system.

Indeed.

> There can be an idea to put defaults values in external file such as `PreferenesDefaults.properties` and developer and manual editor can share its values. This may help document writer to understand behaviors. Is it your concerned?

Yes.

But what matters more than may concern is that people who are involved in development or who want to be involved in development find that modifying preferences is easy.

So, if there is a better (more systematic) way to implement preferences than what exists now we should consider it.

2023-01-30 05:51 UTC, miurahr approved these changes

2023-02-07 09:00 UTC, miurahr commented
I've squashed and merged.

2023-02-07 09:03 UTC, closed without merging