New preferences that are not enabled (need fix)
omegat-org/omegat pull request #436
Opened 2023-01-20 03:31 UTC by brandelune

The 2 commits from the New Defaults PR that require a fix:

https://github.com/omegat-org/omegat/pull/386#issuecomment-1397838660

2023-01-20 05:35 UTC, brandelune commented
The problem with the 2 above settings is that they appear as set, but require a "reset defaults" to be enabled.

2023-01-21 20:44 UTC, briacp commented on src/org/omegat/gui/preferences/view/TagProcessingOptionsController.java
> +        panel.customPatternRegExpTF.setText(Preferences.CHECK_CUSTOM_PATTERN_DEFAULT);
```suggestion
        panel.customPatternRegExpTF.setText(Preferences.getPreferenceDefault(Preferences.CHECK_CUSTOM_PATTERN, Preferences.CHECK_CUSTOM_PATTERN_DEFAULT));
```

2023-01-21 20:44 UTC, briacp commented on src/org/omegat/gui/preferences/view/EditingBehaviorController.java
> +        panel.leaveEmptyRadio.setSelected(!Preferences.isPreference(Preferences.DONT_INSERT_SOURCE_TEXT));
```suggestion
        panel.defaultRadio.setSelected(Preferences.isPreferenceDefault(Preferences.DONT_INSERT_SOURCE_TEXT, false));
        panel.leaveEmptyRadio.setSelected(!Preferences.isPreferenceDefault(Preferences.DONT_INSERT_SOURCE_TEXT, true));
```

2023-01-21 20:44 UTC, briacp commented on src/org/omegat/gui/preferences/view/EditingBehaviorController.java
> +        panel.insertFuzzyCheckBox.setSelected(!Preferences.isPreference(Preferences.BEST_MATCH_INSERT));
```suggestion
        panel.insertFuzzyCheckBox.setSelected(!Preferences.isPreferenceDefault(Preferences.BEST_MATCH_INSERT, true));
```

2023-01-21 22:37 UTC, briacp commented on src/org/omegat/gui/preferences/view/EditingBehaviorController.java
> +        panel.leaveEmptyRadio.setSelected(!Preferences.isPreference(Preferences.DONT_INSERT_SOURCE_TEXT));
Maybe the default true/false values can be refactored as a `Preferences.DONT_INSERT_SOURCE_TEXT_DEFAULT` field, but maybe it's overkill

2023-01-22 06:28 UTC, brandelune reviewed
The preferences are still "visually" set, but not enabled.

It is still necessary to enter the preference panel and "reset defaults" to enable them. Even though visually they are set... Weird.

2023-01-22 12:33 UTC, briacp commented
You're right, the `DONT_INSERT_SOURCE_TEXT` was still using the inverted pref. The 9ab041312f00c672871e976afa169a0c3f9ca10c fix should resolve the problem.

2023-01-22 12:42 UTC, briacp commented
@brandelune just making sure: the new default is "Insert the best fuzzy match" checked by default ?

2023-01-22 13:10 UTC, brandelune commented
> @brandelune just making sure: the new default is "Insert the best fuzzy match" checked by default ?

That's correct.

There are 2 defaults to fix here:
- insert the best fuzzy match
- default custom tag="\d+"

2023-01-22 14:09 UTC, brandelune commented
> There are 2 defaults to fix here:
> 
> * insert the best fuzzy match

This one is not enabled. Thank you.

> * default custom tag="\d+"

This one still requires "reset defaults" to work.

2023-01-22 16:02 UTC, briacp commented
> This one still requires "reset defaults" to work.

good catch the default pref was not used if not set, this is fixed in 4a43876bc17b63a5570d289d1176ff9a6715ce76

2023-01-22 16:32 UTC, brandelune commented
@miurahr I think we're good with this one. Thank you @briacp !!!! 😄

2023-01-23 01:04 UTC, miurahr commented
@brandelune you describe it is "two commits" but there are 10 commits.

2023-01-23 01:27 UTC, miurahr requested changes

2023-01-23 01:27 UTC, miurahr commented on src/org/omegat/util/Preferences.java
> +    public static final boolean DONT_INSERT_SOURCE_TEXT_DEFAULT = false;
It is not put default constant in Preferences class

2023-01-23 01:27 UTC, miurahr commented on src/org/omegat/util/PatternConsts.java
>              if (!"".equalsIgnoreCase(customTagsRegex)) {
Please put TagProcessing behavior defaults in Tag related class.

2023-01-23 01:27 UTC, miurahr commented on src/org/omegat/gui/editor/SegmentBuilder.java
> +                        Preferences.DONT_INSERT_SOURCE_TEXT_DEFAULT);
It is not good to put feature default on Preferences, please put it in SegmentBuilder class as constant.

2023-01-23 04:43 UTC, brandelune commented
> @brandelune you describe it is "two commits" but there are 10 commits.

There were 2 commits originally, and then @briacp added commits to fix the features and the number of commits changed 😄

2023-01-23 06:23 UTC, miurahr requested changes

2023-01-23 06:23 UTC, miurahr commented on src/org/omegat/gui/editor/SegmentBuilder.java
> +                        Preferences.DONT_INSERT_SOURCE_TEXT_DEFAULT);
```suggestion
                        DONT_INSERT_SOURCE_TEXT_DEFAULT);
```

2023-01-23 06:23 UTC, miurahr commented on src/org/omegat/gui/preferences/view/TagProcessingOptionsController.java
> +        panel.customPatternRegExpTF.setText(Preferences.getPreferenceDefault(Preferences.CHECK_CUSTOM_PATTERN, Preferences.CHECK_CUSTOM_PATTERN_DEFAULT));
```suggestion
        panel.customPatternRegExpTF.setText(Preferences.getPreferenceDefault(Preferences.CHECK_CUSTOM_PATTERN, CHECK_CUSTOM_PATTERN_DEFAULT));
```

2023-01-23 06:23 UTC, miurahr commented on src/org/omegat/gui/preferences/view/TagProcessingOptionsController.java
> +        panel.customPatternRegExpTF.setText(Preferences.CHECK_CUSTOM_PATTERN_DEFAULT);
```suggestion
        panel.customPatternRegExpTF.setText(CHECK_CUSTOM_PATTERN_DEFAULT);
```

2023-01-23 06:23 UTC, miurahr commented on src/org/omegat/util/PatternConsts.java
> +            String customTagsRegex = Preferences.getPreferenceDefault(Preferences.CHECK_CUSTOM_PATTERN, Preferences.CHECK_CUSTOM_PATTERN_DEFAULT);
```suggestion
            String customTagsRegex = Preferences.getPreferenceDefault(Preferences.CHECK_CUSTOM_PATTERN, CHECK_CUSTOM_PATTERN_DEFAULT);
```

2023-01-23 06:23 UTC, miurahr commented on src/org/omegat/util/Preferences.java
> +    public static final boolean DONT_INSERT_SOURCE_TEXT_DEFAULT = false;
```suggestion

```

2023-01-23 06:23 UTC, miurahr commented on src/org/omegat/util/Preferences.java
> +    public static final String CHECK_CUSTOM_PATTERN_DEFAULT = "\\d+";
```suggestion

```

2023-01-23 06:34 UTC, brandelune commented
@miurahr With your requested changes, there is this problem:
- "don't insert source" settings appears to be set
- when opening a projet without previous preferences it works
- when clicking on "reset defaults" it appears to not be modified
- but the setting now behaves like "insert source"

2023-01-23 09:53 UTC, briacp commented
The 79760acf3f7c343470b2d6922a8cb62662767dbd commit fix the correct classes of the default prefs values (GitHub PR suggestions only apply on changed lines, it does not allow adding new lines)

2023-01-23 10:23 UTC, brandelune commented
It looks like things work as expected now!
- I run a project with empty OmegaT configuration folder -> things work as expected
- I reset the defaults for each preference in turn -> each time the behavior is as expected

2023-01-24 03:28 UTC, miurahr approved these changes

2023-01-24 03:30 UTC, miurahr commented
I'd like to squash to single commit and merge into master.

2023-01-24 14:44 UTC, miurahr requested changes

2023-01-24 14:44 UTC, miurahr commented on src/org/omegat/util/Preferences.java
> +    /** Tag Validation Option: check user defined tags according to regexp.*/
```suggestion

```

This look like duplication.

2023-01-25 04:03 UTC, miurahr approved these changes

2023-01-25 04:57 UTC, miurahr commented
Squashed and merged into master.

2023-01-25 04:57 UTC, closed without merging