https://github.com/omegat-org/omegat/issues/421
omegat-org/omegat pull request #444
Opened 2023-01-22 16:18 UTC by brandelune

This PR corresponds to the https://github.com/omegat-org/omegat/issues/421 documentation issue.

2023-01-23 01:31 UTC, miurahr requested changes
You describe the commit is updating document, but it modified Bundle.properties.
Please don't change that is not related to the purpose.

2023-01-23 05:24 UTC, brandelune commented
I think we're good now.

2023-01-23 06:14 UTC, miurahr approved these changes

2023-01-23 14:55 UTC, Kazephil commented on src/org/omegat/Bundle.properties
I thought you wanted to name them:
- XLIFF 1.x
- XLIFF 2.x

It's probably fine with XLIFF 2 right below, but just XLIFF might be misinterpreted as applying to all versions of the format.

2023-01-23 15:03 UTC, Kazephil commented on src/org/omegat/Bundle.properties
OK. In that case this is probably ready to be merged if you're happy with the wording tweaks I made in `App_filter.xml`.

2023-01-24 00:05 UTC, Kazephil commented
Merged into `master`.

2023-01-24 00:05 UTC, closed without merging