Change "remove tags" to "hide tags"
omegat-org/omegat pull request #471
Opened 2023-02-10 01:15 UTC by Kazephil

Replace "remove tags" with "hide tags" in the UI, and update the appropriate descriptions in the manual.

2023-02-10 01:50 UTC, brandelune commented
`... will be hidden and you won't have to manipulate them.`

could be a nice addition.

2023-02-10 02:00 UTC, Kazephil commented
> `... will be hidden and you won't have to manipulate them.`

could be a nice addition. 

@brandelune
I just rephrased the entire sentence to include that idea.
Have a look and let me know what you think.

2023-02-14 02:07 UTC, brandelune requested changes

2023-02-14 02:08 UTC, brandelune commented on doc_src/en/Dialogs_ProjectProperties.xml
>  			keep the translated file from opening. If you just need to reduce
I think you should see it now.

2023-02-14 15:25 UTC, Kazephil commented
@brandelune

I think my latest commit covers everything in your comments.

2023-02-15 09:45 UTC, merged