refactor(mt): introduce BaseCachedTranslate class
omegat-org/omegat pull request #474
Opened 2023-02-11 01:40 UTC by miurahr

## Pull request type

- Other (describe below)

refactor

## Which ticket is resolved?

Suggested in PR #470

## What does this PR change?

- Introduce `BaseCachedTranslate` class that has Cache layer.
- Change `BaseTranslate` not to handle cache

2023-02-11 01:46 UTC, miurahr reviewed
These are the changes other than spotless coding style change.

2023-02-11 01:46 UTC, miurahr commented on src/org/omegat/core/machinetranslators/BaseTranslate.java
> -        return getCaffeineCache(name, 1_000, Duration.ONE_DAY);
Removed cache handling code from `BaseTranslate` class.

2023-02-11 01:46 UTC, miurahr commented on src/org/omegat/core/machinetranslators/BaseTranslate.java
> +        return null;
Always return null from `BaseTranslate`

2023-02-11 01:46 UTC, miurahr commented on src/org/omegat/core/machinetranslators/BaseTranslate.java
> +    }
Keep method for backward binary compatibility.

2023-02-11 01:46 UTC, miurahr commented on src/org/omegat/core/machinetranslators/BaseTranslate.java
> +
For future API stability.  see #473

2023-02-11 02:07 UTC, miurahr commented on src/org/omegat/core/machinetranslators/BaseTranslate.java
> +
It seems to be able to be private. I'd like to remove it.

2023-02-11 10:47 UTC, t-cordonnier requested changes
As said in another comment, I would recommend that in BaseCachedTranslate, methods `getTranslation` and `getCachedTranslation` become final, and all cache-related methods become private. This prevents the case where a user overrides getCachedTranslation in a way where the variable `cache` is still here but not used.
Users which don't agree with your cache policy can simply propose an alternative to BaseCachedTranslation class.

Except of that I approve this code.

2023-02-12 02:30 UTC, miurahr commented
> all cache-related methods become private. 

@t-cordonnier  You cannot change `BaseCachedTranslate#getFromCache` and `BaseCachedTranslate#setToCache` method to be private without changing `BaseTranslate#putFromCache` and `BaseTranslate#putToCache`  that breaks binary compatibility against 3rd-party MT plugins that support OmegaT  5.7.1 and before.

Could you suggest a better way?

2023-02-12 03:16 UTC, miurahr commented
@t-cordonnier  does #473 make you satisfied?

2023-02-12 08:02 UTC, t-cordonnier commented
> @t-cordonnier You cannot change `BaseCachedTranslate#getFromCache` and `BaseCachedTranslate#setToCache` method to be private without changing `BaseTranslate#putFromCache` and `BaseTranslate#putToCache` that breaks binary compatibility against 3rd-party MT plugins that support OmegaT 5.7.1 and before.
> 
> Could you suggest a better way?

You can depreciate the method putToCache in BaseTranslate and use a new name in BaseCachedTranslate
Or even depreciate class BaseTranslate and start a new hierarchy

> @t-cordonnier does https://github.com/omegat-org/omegat/pull/473 make you satisfied?

Sorry when I reviewed it I thought it was identical except for adding maxTextLength handling
I will have a new look and tell you later

2023-02-13 00:58 UTC, miurahr commented
A change #473 will be future figure and I think we reach a result;

- make putToCache and getFromCache deprecated  (in 6.1)
- make getCachedTranslate and getTranslate final (in 6.1)
- add getMaxTextLength()
- introduce BaseCachedTranslate class

I've changed last two here,  and plan to first two.

2023-02-16 10:15 UTC, miurahr commented on src/org/omegat/core/machinetranslators/BaseCachedTranslate.java
> +    public final String getCachedTranslation(Language sLang, Language tLang, String text) {
Now the method is final. Adjusted from review comment.

2023-02-17 13:14 UTC, t-cordonnier approved these changes
Looks ok for me now

2023-02-17 14:47 UTC, merged