Bug sf558 incorrect display of rtl segments in fuzzy match pane
omegat-org/omegat pull request #519
Opened 2023-03-13 23:09 UTC by damien-rembert

## Pull request type

- Bug fix -> [bug]

## Which ticket is resolved?

- Incorrect display of RTL segments in the Fuzzy Matches pane
  * [https://sourceforge.net/p/omegat/bugs/558/](https://sourceforge.net/p/omegat/bugs/558/)

## What does this PR change?

- Consolidate methods used for handling bi-directionality in one file
- Apply an orientation to panels/panes as needed

## Other information

Sorry, I realise it's a lot of moving things around but it was the easiest way to get everything tested.
I have tried to keep the commits fairly small so that might help.

2023-03-13 23:31 UTC, damien-rembert commented on src/org/omegat/gui/common/EntryInfoPane.java
> +            CoreEvents.registerFontChangedEventListener(newFont -> setFont(newFont));
No change here, just using a lambda

2023-03-13 23:31 UTC, damien-rembert commented on src/org/omegat/gui/common/EntryInfoPane.java
> +        setComponentOrientation(BiDiUtils.getInitialOrientation());
This is the main change for that PR, it enables this component to handle RTL languages.

2023-03-13 23:31 UTC, damien-rembert commented on src/org/omegat/gui/editor/Document3.java
> -    };
moved to BiDiUtils

2023-03-13 23:31 UTC, damien-rembert commented on src/org/omegat/gui/editor/EditorController.java
no change, just using a lambda

2023-03-13 23:31 UTC, damien-rembert commented on src/org/omegat/gui/editor/EditorController.java
> +            SwingUtilities.invokeLater(() -> ProjectUICommands.projectOpen(projDir, true));
no change, just using a lambda

2023-03-13 23:31 UTC, damien-rembert commented on src/org/omegat/gui/editor/EditorController.java
> +                    files.toArray(new File[files.size()])));
lambda

2023-03-13 23:31 UTC, damien-rembert commented on src/org/omegat/gui/editor/EditorController.java
> +        applyOrientationToEditor(currentOrientation);
Moved to BiDiUtils

2023-03-13 23:31 UTC, damien-rembert commented on src/org/omegat/gui/editor/EditorController.java
> +        currentOrientation = BiDiUtils.getOrientationType();
no functional change, just moved to BiDiUtils

2023-03-13 23:31 UTC, damien-rembert commented on src/org/omegat/gui/editor/EditorController.java
> -        activateEntry();
This was never used.

2023-03-13 23:31 UTC, damien-rembert commented on src/org/omegat/gui/editor/EditorController.java
> +        String country = Language.getUpperCaseCountryFromLocale();
No functional change

2023-03-13 23:31 UTC, damien-rembert commented on src/org/omegat/gui/matches/MatchesVarExpansion.java
> +                r.text = r.text.replace(VAR_DIFF, diffRender.text);
Use a lambda

2023-03-13 23:31 UTC, damien-rembert commented on src/org/omegat/gui/matches/MatchesVarExpansion.java
> +        r.text = r.text.replace(VAR_SOURCE_TEXT, match.source);
lambda

2023-03-13 23:31 UTC, damien-rembert commented on src/org/omegat/gui/matches/MatchesVarExpansion.java
> +    };
The two Replacers above handle different text directionality.

2023-03-13 23:31 UTC, damien-rembert commented on src/org/omegat/gui/matches/MatchesVarExpansion.java
> +                r.text = r.text.replace(VAR_DIFF_REVERSED, diffRender.text);
lambda

2023-03-13 23:31 UTC, damien-rembert commented on src/org/omegat/gui/matches/MatchesVarExpansion.java
> +                match.creator == null ? "" : match.creator);
formatting

2023-03-13 23:31 UTC, damien-rembert commented on src/org/omegat/gui/matches/MatchesVarExpansion.java
> +                Integer.toString(match.scores[0].adjustedScore));
formatting

2023-03-13 23:31 UTC, damien-rembert commented on src/org/omegat/gui/matches/MatchesVarExpansion.java
> +        }
check if bi-directionality is needed and if so what type

2023-03-14 03:26 UTC, brandelune commented
I can't do much code reviewing here, so I'll be waiting for Manuel to give us input on how he sees the code behaving. Thank you Damien.

2023-03-14 23:33 UTC, damien-rembert commented
Yep it would be nice if somebody could test this with RTL languages as I couldn't do much. I might ask the mailing list if someone can help with that.

2023-03-15 16:10 UTC, damien-rembert commented
No worries, I'm happy for this to be shelved until 6.1 :)
It totally makes sense to stop adding features before a release.
Most changes were done to improve legibility or testability.
Hopefully this will also enable us to have something closer to what happens in the editor where each direction (RTL or LTR) is appropriately left or right aligned.

2023-05-16 12:16 UTC, miurahr commented
I'd like to check each commit. Could you wait for my reading 24 commits.  If you can make changes smaller, it will help my review process.

2023-05-23 08:46 UTC, damien-rembert commented
Sorry, I have not had much time lately but I'll try to make the changes smaller as soon as possible.

2023-05-27 12:12 UTC, miurahr commented on src/org/omegat/gui/matches/MatchesVarExpansion.java
> +                Integer.toString(match.scores[0].adjustedScore));
Spotless may change.

2023-06-04 13:46 UTC, miurahr commented
reviewed from start to a3c59596b677efa265dfb9264febd24892106ad2.

2023-06-24 08:47 UTC, miurahr requested changes

2023-06-24 08:47 UTC, miurahr commented on src/org/omegat/util/Language.java
> -    public static boolean localeIsRTL() {
To keep backward compatibility, please leave the method. It can be call `BiDiUtils#localeIsRTL`

2023-06-24 08:47 UTC, miurahr commented on src/org/omegat/util/Language.java
> -    public static boolean isRTL(final String language) {
To keep backward compatibility, please leave the method.
you can add `@deprecated`

2023-06-24 08:56 UTC, miurahr requested changes

2023-06-24 08:56 UTC, miurahr commented on src/org/omegat/gui/common/EntryInfoPane.java
> +    protected EntryInfoPane(final boolean useApplicationFont) {
Please don't change visibility.

2023-06-24 08:56 UTC, miurahr commented on test/src/org/omegat/gui/matches/MatchesVarExpansionTest.java
> +import static org.junit.Assert.*;
PLease use single imports

2023-06-24 08:56 UTC, miurahr commented on test/src/org/omegat/util/BiDiUtilsTest.java
> +	final Language LTR_LANGUAGE = new Language("pl");
Please indent 4 space characters

2023-06-24 09:00 UTC, miurahr commented on src/org/omegat/gui/editor/EditorUtils.java
> +            s.append(BiDiUtils.BIDI_LRM_CHAR);
There seems no active reason to copy constant to BiDiUtils class.

2023-06-24 09:07 UTC, miurahr commented
@damien-rembert  Please check a branch https://github.com/omegat-org/omegat/tree/topic/damien/add-bidi-utils
that is rebased on master, and recreate a clean commits .

2023-07-03 23:35 UTC, miurahr commented
I've pushed PR for your convenience.
https://github.com/omegat-org/omegat/pull/669

2023-07-06 06:45 UTC, miurahr commented
I want ot merge  #669 as successor of here.

2023-07-06 06:45 UTC, closed without merging