docs(first step): remove version string from First_Step
omegat-org/omegat pull request #548
Opened 2023-04-24 22:14 UTC by miurahr

When show on OmegaT version number in First step article, it should be as same as OmegaT release version.
Current version number is set from manual version, that is incorrect.

## Pull request type

Please mark github LABEL of the type of change your PR introduces:

- Bug fix -> [bug]
- Feature enhancement -> [enhancement]
- Documentation -> [documentation]
- Build and release changes -> [build/release]
- Other (describe below)

## Which ticket is resolved?

-  First step document show wrong OmegaT version
  * https://sourceforge.net/p/omegat/documentation/409/

## What does this PR change?

- Remove referece to manual version.
-
-

## Other information

2023-04-24 23:00 UTC, brandelune requested changes
I'm not sure I understand the problem. The version number is automatically corrected during the build process.

Plus, I don't think that we should add strings, even in the title. People know what OmegaT is.

2023-04-26 07:31 UTC, miurahr commented
> The version number is automatically corrected during the build process.

No. it is replaced with wrong document version, not a omegat software version.

2023-04-26 12:52 UTC, miurahr commented
> > The CSS files should not be changed. Only the file here: https://github.com/omegat-org/omegat/blob/master/doc_src/OmegaT_new.css
> > should be changed.
> 
> I don't change a source file, just run build process. If it should not be chaged, there may be a bug in document build script.

https://github.com/omegat-org/omegat/commit/c8b574bd1fbdb6232b23d1ca5e58b88e5a034935

Then souce css was changed by @Kazephil  last week and only update an english build results, but not against other languages.

2023-04-29 22:33 UTC, miurahr commented
I remake PR only with a removal of version number.

2023-04-30 03:49 UTC, brandelune approved these changes

2023-04-30 07:31 UTC, merged