chore: (trial)  Arm Mac JRE 11 bundled distribution
omegat-org/omegat pull request #680
Opened 2023-07-08 07:43 UTC by miurahr

## Pull request type

- Build and release changes -> [build/release]

## Which ticket is resolved?

## What does this PR change?

-  Configure tasks armMacDistZip armMacNotarize armMacSignedDistZip and armMacStapledNotarizedDistZip
-  default target "mac" includes armMac distribution

## Other information

2023-07-08 08:48 UTC, brandelune reviewed
I only have an intel machine. I can't test.

2023-07-08 12:40 UTC, kosivantsov requested changes
It would be good if both zip distributions for Mac were clearly marked as to what architecture they are intended for:
OmegaT_x.x.x_Mac_x64.zip
OmegaT_x.x.x_Mac_arm.zip

2023-07-12 00:10 UTC, miurahr commented
> I only have an intel machine. I can't test.

Now we generate universal launcher binary `OmegaT.app/Contents/MacOS/OmegaT` and resources when build time.
@brandelune  could you test it to check a degrade.

@kosivantsov I've adjusted a suffix reflect your comment.

2023-07-12 00:11 UTC, miurahr commented on build.gradle
> +    archiveFileName.set("${applicationName}_${project.version}${omtVersion.beta}_Mac_x86.zip")
```suggestion
    archiveFileName.set("${applicationName}_${project.version}${omtVersion.beta}_Mac_x64.zip")
```

Here is a typo.

2023-07-12 00:16 UTC, miurahr commented
Most of `OmegaT.app` bundle files are generated into `build/appbundler` and pack into `..._Mac_x64.zip` and `..._Mac_arm.zip` distribution with proper JRE.

@brandelune  Please place Java 11 runtime for x64 mac on a directory where OmegaT repository directory exists.
https://adoptium.net/download/

For test, please run `./gradlew mac`

2023-07-12 03:48 UTC, miurahr commented
Commit d4baa7eba816abbcfd0bd60e57a9b2c699a46c83 come from #679

2023-07-13 02:45 UTC, miurahr commented
Now launcher become an universal binary

2023-07-13 13:49 UTC, miurahr commented
There are artifacts which are built with proposed changes.

- [OmegaT_6.1.0_Beta_Mac_arm.zip](https://omegat.sourceforege.io/temporary/OmegaT_6.1.0_Beta_Mac_arm.zip) 345M
- [OmegaT_6.1.0_Beta_Mac_x64.zip](https://omegat.sourceforege.io/temporary/OmegaT_6.1.0_Beta_Mac_x64.zip) 346M

2023-07-13 13:51 UTC, miurahr commented
@brandelune  could you check x64 version not to break Icons, messages and execution on Intel Mac?

@kosivantsov  could you check arm version?

2023-07-13 13:53 UTC, brandelune commented
The links don't seem to work.

2023-07-13 13:55 UTC, brandelune commented
Proper link is here:
https://omegat.sourceforge.io/temporary/OmegaT_6.1.0_Beta_Mac_x64.zip
https://omegat.sourceforge.io/temporary/OmegaT_6.1.0_Beta_Mac_arm.zip

But there is an error message:

`Files on SourceForge.net Project Web sites are limited to a max size. The file requested is too large. If you are the project administrator, you should host your large files using the File Release Service, not Project Web. Contact [SourceForge.net support](http://sourceforge.net/support/) for assistance.`

2023-07-16 05:59 UTC, miurahr commented
I'd like to remove files on project web because sourceforge don't support it.

2023-07-16 06:05 UTC, miurahr commented
@brandelune could you suggest where I can put  a 350MB package for you?

2023-07-16 06:12 UTC, brandelune commented
> @brandelune could you suggest where I can put a 350MB package for you?

Do you have a private FTP site somewhere?

2023-07-26 23:43 UTC, miurahr commented on build.gradle
> +            argument(value: '--config-file=${configfile}')
It seems not working. There is no definition "configfile" and it does not replace with variable because string has single quote.

2023-07-26 23:50 UTC, miurahr commented
> Do you have a private FTP site somewhere?

no. you can build it by yourself.

2023-07-31 14:19 UTC, miurahr commented
arm https://drive.proton.me/urls/DP07WEFG98#Ns0qqjZLIl7l
intel https://drive.proton.me/urls/YGXYH1398M#TBE3FGroCWzH

2023-07-31 19:09 UTC, brandelune commented
> arm https://drive.proton.me/urls/DP07WEFG98#Ns0qqjZLIl7l
> intel https://drive.proton.me/urls/YGXYH1398M#TBE3FGroCWzH

The intel version seems to work well.

2023-08-01 13:42 UTC, miurahr commented
when intel version working, there is no defeat. We can provide new value for users.
If no objection, I'd like to ask users feedback on weekly version.

2023-08-01 14:25 UTC, kosivantsov commented
> arm https://drive.proton.me/urls/DP07WEFG98#Ns0qqjZLIl7l
> intel https://drive.proton.me/urls/YGXYH1398M#TBE3FGroCWzH

Arm version works well too.

2023-08-02 04:37 UTC, merged

2023-08-02 09:31 UTC, brandelune commented
The only (small) issue I have with this packaging is the location/URI of the manual pages when they are displayed in the browser.

2023-08-02 22:17 UTC, miurahr commented
> The only (small) issue I have with this packaging is the location/URI of the manual pages when they are displayed in the browser.

Is the thing specific to the packaging? Is a  behavior observed in distribution without JRE?

2023-08-03 05:44 UTC, brandelune commented
The path with the packaging is:

file:///private/var/folders/q2/qvrspt8x5r7gqj7_3_b3hqm80000gq/T/AppTranslocation/9F41BDB0-5EE4-4292-85F5-52517EE2C97C/d/OmegaT.app/Contents/Java/docs/en/index.html

Without the packaging it is:
file:///Users/suzume/Downloads/OmegaT_6.1.0_Beta_Mac_x64/OmegaT.app/Contents/Java/docs/en/index.html

In both cases, the binary is taken from the Downloads directory.

2023-08-03 13:02 UTC, miurahr commented
There is an idea that contents can be extracted in  `docs/<lang>/` on application at first time,  and reuse it  in second time.
I wandering OmegaT has a permission to write into application folder.