ui: TagProcessingOptionsPanel to TextArea
omegat-org/omegat pull request #764
Opened 2023-10-09 07:43 UTC by miurahr

There are two text field in TagProcessingOptionsPanel. This change these to textarea.

## Pull request type

Please mark github LABEL of the type of change your PR introduces:

- Bug fix -> [bug]
- Feature enhancement -> [enhancement]
- Documentation -> [documentation]
- Build and release changes -> [build/release]
- Other (describe below)

## Which ticket is resolved?

- Title ex. fix...
  * URL ex. https://...
 
- Title
  * URL

## What does this PR change?

-
-
-

## Other information

2023-10-17 21:06 UTC, miurahr commented
There is a different request to solve similar issue that regex is longer than the field.

The request "BUGS#1146 Custom tag field does not resize based on contents" asks size of text field.

[RFE#1445 Multiple-value input/editor for custom tags](https://sourceforge.net/p/omegat/feature-requests/1445/) propose  changing custom tag fields to be a table.

2023-10-18 02:49 UTC, brandelune requested changes
The text area needs to wrap otherwise the result is similar to what we had before: the need to scroll to the right to see the end of the expression.

2023-10-18 05:52 UTC, miurahr commented
> The text area needs to wrap otherwise the result is similar to what we had before: the need to scroll to the right to see the end of the expression.

Any change suggestions?

2023-10-18 05:58 UTC, brandelune commented
> > The text area needs to wrap otherwise the result is similar to what we had before: the need to scroll to the right to see the end of the expression.
> 
> Any change suggestions?

Yes:

> > The text area needs to wrap

2023-10-18 09:50 UTC, miurahr commented
> > > The text area needs to wrap otherwise the result is similar to what we had before: the need to scroll to the right to see the end of the expression.
> > 
> > 
> > Any change suggestions?
> 
> Yes:
> 
> > > The text area needs to wrap

I do not know how to do it.

2023-10-18 10:31 UTC, miurahr commented
There is similar ticket that request for custom tag edit.
https://sourceforge.net/p/omegat/feature-requests/1445/

2023-10-18 11:03 UTC, brandelune commented
> There is similar ticket that request for custom tag edit. https://sourceforge.net/p/omegat/feature-requests/1445/

I saw it. It's interesting.

Right now the function works as expected. I think that the priority should go to have "project specific" custom tags, before having all the nice refinements for editing.

2023-10-19 01:42 UTC, miurahr commented
> I think that the priority should go to have "project specific" custom tags, before having all the nice refinements for editing.

There is a big gap that OmegaT have never support project specific `preferences` yet,  because segmentation(SRX) and filter(filters.xml) has its specific config files. 

To implement the feature "project specific" custom tags, it is necessary to make big changes in OmegaT core of preferences management subsystem.

2023-10-19 02:52 UTC, brandelune commented
> To implement the feature "project specific" custom tags, it is necessary to make big changes in OmegaT core of preferences management subsystem.

I think we can do it more smartly, by using what OmegaT already provides.

OmegaT provides user with the ability to set a configuration folder on the command line. But using the command line is not trivial for users.

So, if we had a dialog in the project properties that has "use project specific settings", OmegaT would simply use a project specific configuration folder.

We can discuss that on dev because it is slightly off topic here.

2023-11-05 12:08 UTC, miurahr commented
@brandelune when you realize what you want, please raise PR.

2023-11-05 12:08 UTC, closed without merging